### ISSUE TITLE
Use of .Net API and pattern

### ISSUE THREAD

**Issue by WenceyWang** [Infinideastudio/NEWorld.Net#2]
There are a lot of API in .Net and can be used directly.

I think it is better to use those type in System.Numerics instead of writing your own Vec<T> or something else.

And there are also some pattern like this [Dispose Pattern](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern) can be use instead of writing some confusing classes.

**Comment by DWVoid** [comment]
Well, basically this classes are kept forcode migration purposes. They will be removed after the second round of refactoring after I make sure everything works properly.

**Comment by DWVoid** [comment]
Refactor on this part is completed
